baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Zoe Maternidade" # Título corrigido

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# Correção para forçar a publicação de posts (bug do fuso horário)
buildFuture = true

[params]
  images = ["img/og-image.jpg"]
