baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Zoe Maternidade" # <<< Mudei o título para si
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  images = ["img/og-image.jpg"]

# Força a publicação de posts
buildFuture = true

# ESTA É A CORREÇÃO: Adiciona um link no menu
[[menu.main]]
  name = "Conteúdo"
  url = "/blog"
  weight = 1
