# Configuração do Backend (Onde salvar)
backend:
  name: git-gateway
  branch: main # O seu branch principal

# Configuração de Mídia (Onde salvar imagens)
media_folder: "exampleSite/static/images/uploads"
public_folder: "/images/uploads"

# Configuração de Coleções (Onde você vai escrever)
collections:
  # Coleção específica PARA MÃES (Antigo "Blog")
  - name: "maes"
    label: "Conteúdo para Mães"
    folder: "exampleSite/content/maes" # Onde os posts das mães serão guardados
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Capa", name: "image", widget: "image", optional: true }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  # Coleção específica PARA PAIS (A nova secção)
  - name: "pais"
    label: "Conteúdo para Pais"
    folder: "exampleSite/content/pais" # Onde os posts dos pais serão guardados
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Capa", name: "image", widget: "image", optional: true }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
