backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # O padrão que você encontrou
public_folder: "img"

collections:
  - name: "conteudo"
    label: "Conteúdo (Mães e Pais)" # Um só lugar para publicar
    folder: "site/content/post" # <<< A "MALDITA SOLUÇÃO"
    path: "{{slug}}/index" # O padrão que você encontrou
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      # AQUI ESTÁ A MAGIA:
      - label: "Categorias"
        name: "categories"
        widget: "list"
        allow_add: false # Não deixa criar categorias novas
        options: # As únicas opções
          - "Mães"
          - "Pais"
      # FIM DA MAGIA
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "hidden", default: false} # Correção do "Rascunho"
